# Generated by Django 5.0.1 on 2024-03-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_typeofbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='typeofbook',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
