# Generated by Django 5.0.1 on 2024-03-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_typeofbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookauthor',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='bookrating',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
