# Generated by Django 5.0.1 on 2024-03-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_bookauthor_post_bookrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='booktagline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
