# Generated by Django 5.0.1 on 2024-04-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_bookauthor_alter_post_bookrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='booktagline',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
