# Generated by Django 4.1.2 on 2022-11-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='author',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='addblog',
            name='slug',
            field=models.CharField(max_length=130),
        ),
    ]
