# Generated by Django 5.0.1 on 2024-03-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_addblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
