# Generated by Django 5.0.1 on 2024-03-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_addblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='addblog',
            name='type',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
