# Generated by Django 5.0.1 on 2024-03-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_addblog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addblog',
            name='type',
        ),
        migrations.AddField(
            model_name='addblog',
            name='typeofbook',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
